name: DSC180a-q1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - torchvision
  - ipykernel
  - ipywidgets
  - pip:
    - torch
    - torchvision
    - argparse
    - datetime
    - pathlib
    - numpy
    - matplotlib
    - pycocotools
    - scikit-image
    - pandas
    - seaborn
    - pillow

